function renderProgress(){const pct=totalProgress();$('#progressPct').textContent=pct+'%';$('#progressRing').style.setProperty('--p',pct);$('#progressHeadline').textContent=pct===0?'Empezando':pct<35?'Construyendo bases':pct<70?'Buen progreso':'Obediencia avanzada';$('#progressText').textContent=`${solidCount()} de ${COMMANDS.length} comandos están consistentes o mejor.`;$('#progressList').innerHTML=COMMANDS.map(c=>`<article class="progressRow"><div><strong>${escapeHtml(c.cmd)} · <span class="pronunciation">${escapeHtml(c.pron)}</span></strong><small>Nivel ${c.level} · ${escapeHtml(c.meaning)}</small></div><select data-state="${escapeHtml(c.cmd)}">${STATES.map(s=>`<option ${stateOf(c.cmd)===s?'selected':''}>${s}</option>`).join('')}</select></article>`).join('');$$('[data-state]').forEach(s=>s.onchange=()=>{progress[s.dataset.state]=s.value;store.set('patrickProgress',progress);renderAll()})}
function updateRolling(cmd,correct){const arr=trials[cmd]||[];arr.push(correct?1:0);trials[cmd]=arr.slice(-10);store.set('patrickTrials',trials);if(stateOf(cmd)==='No iniciado'){progress[cmd]='En práctica'}if(trials[cmd].length>=10&&trials[cmd].reduce((a,b)=>a+b,0)>=8&&STATE_SCORE[stateOf(cmd)]<2){progress[cmd]='Consistente'}store.set('patrickProgress',progress)}
function startSession(cmds=focusForLevel(currentLevel)){if(!cmds.length)return;session={commands:cmds,index:0,trial:0,results:{}};cmds.forEach(c=>session.results[c.cmd]=[]);$('#sessionDialog').showModal();renderSessionStep()}
function renderSessionStep(){const c=session.commands[session.index];const total=session.commands.length;$('#sessionCounter').textContent=`${session.index+1} de ${total}`;$('#sessionCommandTitle').textContent=c.cmd;$('#sessionCategory').textContent=`Nivel ${c.level} · ${c.category}`;$('#sessionPron').textContent=c.pron;$('#sessionMeaning').textContent=c.meaning;$('#sessionSignal').textContent=c.signal;$('#sessionAction').textContent=c.action;$('#sessionHow').textContent=c.how;$('#sessionReward').textContent=c.reward;$('#trialCounter').textContent=`${session.trial}/5`;const done=session.index*5+session.trial;$('#sessionProgressBar').style.width=`${Math.round(done/(total*5)*100)}%`;$('#sessionAudioBtn').onclick=()=>speak(c)}
function recordTrial(correct){const c=session.commands[session.index];session.results[c.cmd].push(correct);updateRolling(c.cmd,correct);session.trial++;if(session.trial>=5){session.index++;session.trial=0;if(session.index>=session.commands.length){finishSession();return}}renderSessionStep()}
function finishSession(){const stamp={at:new Date().toISOString(),level:currentLevel,results:{}};Object.entries(session.results).forEach(([cmd,arr])=>stamp.results[cmd]={correct:arr.filter(Boolean).length,total:arr.length});history.unshift(stamp);history=history.slice(0,30);store.set('patrickHistory',history);$('#sessionDialog').close();$('#finishSummary').textContent='Guardé los resultados y actualicé el progreso de las últimas 10 repeticiones.';$('#finishResults').innerHTML=Object.entries(stamp.results).map(([cmd,r])=>`<div class="finishResult"><strong>${escapeHtml(cmd)}</strong><span>${r.correct}/${r.total} correctas</span></div>`).join('');$('#finishDialog').showModal();renderAll()}
function renderAll(){renderToday();renderLevels();renderProgress();if($('#commands').classList.contains('active'))renderCommands()}
function exportProgress(){const payload={version:1,exportedAt:new Date().toISOString(),progress,trials,history,currentLevel,dayType};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='patrick-training-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Respaldo descargado')}
function resetProgress(){if(!confirm('¿Reiniciar todo el progreso y sesiones de Patrick?'))return;progress={};trials={};history=[];currentLevel=0;['patrickProgress','patrickTrials','patrickHistory','patrickCurrentLevel'].forEach(k=>localStorage.removeItem(k));renderAll();toast('Progreso reiniciado')}
function init(){if(store.get('patrickDark',window.matchMedia('(prefers-color-scheme: dark)').matches))document.body.classList.add('dark');$('#dayType').value=dayType;$$('.bottomNav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('#dayType').onchange=e=>{dayType=e.target.value;store.set('patrickDayType',dayType);renderToday()};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');store.set('patrickDark',document.body.classList.contains('dark'))};$('#startSessionBtn').onclick=()=>startSession();$('#advanceBtn').onclick=()=>{if(currentLevel<10){currentLevel++;store.set('patrickCurrentLevel',currentLevel);renderAll();toast(`Nivel ${currentLevel} activado`)}};$('#search').oninput=renderCommands;$('#closeSessionBtn').onclick=()=>{if(confirm('¿Salir de la sesión actual?'))$('#sessionDialog').close()};$('#retryBtn').onclick=()=>recordTrial(false);$('#correctBtn').onclick=()=>recordTrial(true);$('#finishBtn').onclick=()=>{$('#finishDialog').close();setView('today')};$('#exportBtn').onclick=exportProgress;$('#resetBtn').onclick=resetProgress;renderCommands();renderAll()}
init();
