const COMMANDS=window.PATRICK_COMMANDS;
const LEVELS=window.PATRICK_LEVELS;
const STATES=['No iniciado','En práctica','Consistente','Generalizando','Dominado'];
const STATE_SCORE={'No iniciado':0,'En práctica':1,'Consistente':2,'Generalizando':3,'Dominado':4};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let progress=store.get('patrickProgress',{}), trials=store.get('patrickTrials',{}), history=store.get('patrickHistory',[]), currentLevel=store.get('patrickCurrentLevel',0), dayType=store.get('patrickDayType','Todo el día'), filter='Todos';
let session=null, toastTimer=null;
function stateOf(cmd){return progress[cmd]||'No iniciado'}
function commandBy(name){return COMMANDS.find(c=>c.cmd===name)}
function levelBy(n){return LEVELS.find(l=>l.n===n)}
function escapeHtml(s=''){return s.replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function speak(c){if(!('speechSynthesis'in window)){toast('Tu navegador no tiene voz disponible');return} speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(c.cmd.replace('!',''));u.lang='de-DE';u.rate=.72;const voices=speechSynthesis.getVoices();const de=voices.find(v=>v.lang?.toLowerCase().startsWith('de'));if(de)u.voice=de;speechSynthesis.speak(u)}
function levelProgress(n){const cmds=levelBy(n).commands;if(!cmds.length)return 0;return Math.round(cmds.reduce((a,x)=>a+STATE_SCORE[stateOf(x)]/4,0)/cmds.length*100)}
function levelReady(n){return levelBy(n).commands.every(x=>STATE_SCORE[stateOf(x)]>=2)}
function totalProgress(){return Math.round(COMMANDS.reduce((a,c)=>a+STATE_SCORE[stateOf(c.cmd)]/4,0)/COMMANDS.length*100)}
function solidCount(){return COMMANDS.filter(c=>STATE_SCORE[stateOf(c.cmd)]>=2).length}
function focusForLevel(n){const names=levelBy(n).commands;const pending=names.map(commandBy).filter(c=>STATE_SCORE[stateOf(c.cmd)]<2);return (pending.length?pending:names.map(commandBy)).slice(0,dayType==='Solo noche'?2:3)}
function microPlan(){const f=focusForLevel(currentLevel);const known=COMMANDS.filter(c=>c.level<currentLevel&&STATE_SCORE[stateOf(c.cmd)]>=2).slice(-2);if(dayType==='Solo noche')return[
['Al llegar','4–5 min','Nuevo + fácil',[f[0],known.at(-1)].filter(Boolean)],
['Más tarde','4–5 min','Segundo foco + repaso',[f[1]||f[0],known.at(-2)].filter(Boolean)],
['Antes de dormir','1–2 min','Una victoria fácil',[known.at(-1)||f[0]].filter(Boolean)]
];return[
['Mañana','3–5 min','Foco principal',[f[0],known.at(-1)].filter(Boolean)],
['Mediodía','3–5 min','Control / calma',[f.find(c=>['Control','Autocontrol','Casa'].includes(c.category))||f[1]||f[0]].filter(Boolean)],
['Tarde','3–5 min','Segundo foco',[f[1]||f[0]].filter(Boolean)],
['Noche','2–4 min','Repaso fácil + juego',[known.at(-1)||f.at(-1)].filter(Boolean)]
]}
function setView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'});if(id==='progress')renderProgress();if(id==='commands')renderCommands();if(id==='levels')renderLevels()}
function renderToday(){const l=levelBy(currentLevel),ready=levelReady(currentLevel);$('#headerLevel').textContent=`Nivel ${currentLevel} · ${l.title}`;$('#todaySummary').textContent=dayType==='Solo noche'?'Plan corto para cuando llegas en la noche.':'Micro-sesiones repartidas durante el día.';$('#dayType').value=dayType;$('#levelBadge').textContent=`Nivel ${currentLevel}`;$('#readinessBadge').textContent=ready&&currentLevel<10?'Listo para avanzar':'En curso';$('#readinessBadge').classList.toggle('ready',ready);$('#sessionTitle').textContent=l.title;$('#sessionGoal').textContent=l.goal;const focus=focusForLevel(currentLevel);$('#focusCommands').innerHTML=focus.map(c=>`<span class="focusChip">${escapeHtml(c.cmd)} <small>${escapeHtml(c.pron)}</small></span>`).join('');$('#metricProgress').textContent=totalProgress()+'%';$('#metricSolid').textContent=solidCount();$('#metricSessions').textContent=history.length;$('#todayPlan').innerHTML=microPlan().map(([name,dur,goal,cmds],i)=>`<article class="planItem"><span class="planNumber">${i+1}</span><div><strong>${name} · ${goal}</strong><p>${cmds.map(c=>c.cmd).join(' · ')||'Juego y vínculo'}</p></div><small>${dur}</small></article>`).join('');const adv=$('#advanceCard');adv.hidden=!(ready&&currentLevel<10)}
function renderLevels(){$('#levelList').innerHTML=LEVELS.map(l=>{const p=levelProgress(l.n);return `<article class="levelCard ${currentLevel===l.n?'activeLevel':''}"><div class="levelTop"><span class="levelIndex">${l.n}</span><div class="levelTitleWrap"><strong>${escapeHtml(l.title)}</strong><small>${escapeHtml(l.goal)}</small></div><span class="levelProgress">${p}%</span></div><div class="miniBar"><div style="width:${p}%"></div></div><div class="levelCommands">${l.commands.map(n=>`<span class="tinyChip">${escapeHtml(n)} · ${escapeHtml(commandBy(n).pron)}</span>`).join('')}</div><div class="levelActions">${currentLevel===l.n?'<span class="badge">Nivel activo</span>':`<button class="setLevelBtn" data-set-level="${l.n}">Trabajar este nivel</button>`}</div></article>`}).join('');$$('[data-set-level]').forEach(b=>b.onclick=()=>{currentLevel=+b.dataset.setLevel;store.set('patrickCurrentLevel',currentLevel);renderAll();toast(`Nivel ${currentLevel} activado`)})}
function categories(){return ['Todos',...new Set(COMMANDS.map(c=>c.category))]}
function commandCard(c){return `<article class="commandCard" data-command="${escapeHtml(c.cmd)}"><div class="commandSummary"><div><div class="commandTitle"><strong>${escapeHtml(c.cmd)}</strong><span class="pronunciation">${escapeHtml(c.pron)}</span></div><div class="commandMeaning">${escapeHtml(c.meaning)}</div><div class="commandMeta"><span class="tinyChip">Nivel ${c.level}</span><span class="tinyChip">${escapeHtml(c.category)}</span></div></div><div class="commandActions"><button class="audioBtn" data-audio="${escapeHtml(c.cmd)}" aria-label="Escuchar ${escapeHtml(c.cmd)}">🔊</button><button class="practiceBtn" data-practice="${escapeHtml(c.cmd)}" aria-label="Practicar ${escapeHtml(c.cmd)}">▶</button></div></div><button class="commandToggle" data-toggle="${escapeHtml(c.cmd)}">Ver cómo enseñarlo <span>＋</span></button><div class="commandDetails"><div class="detailRow"><strong>Señal / gesto</strong><p>${escapeHtml(c.signal)}</p></div><div class="detailRow"><strong>Qué debe hacer</strong><p>${escapeHtml(c.action)}</p></div><div class="detailRow"><strong>Paso a paso</strong><p>${escapeHtml(c.how)}</p></div><div class="detailRow"><strong>Premio</strong><p>${escapeHtml(c.reward)}</p></div><div class="detailRow"><strong>Criterio de avance</strong><p>Acumula al menos 8 aciertos en las últimas 10 repeticiones antes de subir dificultad.</p></div></div></article>`}
function renderCommands(){const q=$('#search').value.trim().toLowerCase();$('#filters').innerHTML=categories().map(x=>`<button class="filterBtn ${filter===x?'active':''}" data-filter="${escapeHtml(x)}">${escapeHtml(x)}</button>`).join('');const arr=COMMANDS.filter(c=>(filter==='Todos'||c.category===filter)&&(`${c.cmd} ${c.pron} ${c.meaning} ${c.category}`).toLowerCase().includes(q));$('#commandList').innerHTML=arr.map(commandCard).join('')||'<p class="muted">No encontré comandos con ese filtro.</p>';$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderCommands()});$$('[data-audio]').forEach(b=>b.onclick=()=>speak(commandBy(b.dataset.audio)));$$('[data-practice]').forEach(b=>b.onclick=()=>startSession([commandBy(b.dataset.practice)]));$$('[data-toggle]').forEach(b=>b.onclick=()=>{const card=b.closest('.commandCard');card.classList.toggle('open');b.querySelector('span').textContent=card.classList.contains('open')?'−':'＋'})}
